//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFP4FLauncherWV.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BFP4FLauncherWV.Resources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 01.02.2019_2242 
        /// ähnelt.
        /// </summary>
        internal static string BuildDate {
            get {
                return ResourceManager.GetString("BuildDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die +webSiteHostName &quot;#IP#&quot; +battleFundsHostName &quot;#IP#&quot; +survey 0 +dc 1 +sessionId #SESSION# +lang en +soldierName &quot;#PLAYER#&quot; +multi 1 +frontendUrl &quot;http://#IP#:1234/&quot; +autoLogin 1 +loggedIn &quot;true&quot; +webBrowser 0 +magmaProtocol http +magmaHost #IP# +punkBuster 0 ähnelt.
        /// </summary>
        internal static string client_startup {
            get {
                return ResourceManager.GetString("client_startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] redi {
            get {
                object obj = ResourceManager.GetObject("redi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #IP#    jeff.easylocaldev.com
        ///#IP#    battlefield.play4free.com
        ///#IP#    dev.easy.ea.com
        ///#IP#    dev2.easy.ea.com
        ///#IP#    dev3.easy.ea.com
        ///#IP#    dev4.easy.ea.com
        ///#IP#    playtest1.easy.ea.com
        ///#IP#    playtest1.easy.ea.com
        ///#IP#    private.battlefield.play4free.com
        ///#IP#    preprod.battlefield.play4free.com
        ///#IP#    pte.battlefield.play4free.com
        ///#IP#    gosredirector.ea.com
        ///#IP#    peach.online.ea.com
        ///#IP#    nexus.passport.com ähnelt.
        /// </summary>
        internal static string template_hosts_file {
            get {
                return ResourceManager.GetString("template_hosts_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HTTP/1.1 200 OK
        ///Content-Type: application/xml
        ///X-BLAZE-COMPONENT: qos
        ///X-BLAZE-COMMAND: qos
        ///Content-Length: #SIZE#
        ///X-BLAZE-SEQNO: 0
        ///
        /// ähnelt.
        /// </summary>
        internal static string template1 {
            get {
                return ResourceManager.GetString("template1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;qos&gt;
        ///    &lt;numprobes&gt;0&lt;/numprobes&gt;
        ///    &lt;qosport&gt;17499&lt;/qosport&gt;
        ///    &lt;probesize&gt;0&lt;/probesize&gt;
        ///    &lt;qosip&gt;#QOSIP#&lt;/qosip&gt;
        ///    &lt;requestid&gt;1&lt;/requestid&gt;
        ///    &lt;reqsecret&gt;0&lt;/reqsecret&gt;
        ///&lt;/qos&gt;
        /// ähnelt.
        /// </summary>
        internal static string template2 {
            get {
                return ResourceManager.GetString("template2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HTTP/1.1 200 OK
        ///Content-Type: application/xml
        ///X-BLAZE-COMPONENT: qos
        ///X-BLAZE-COMMAND: qos
        ///Content-Length: #SIZE#
        ///X-BLAZE-SEQNO: 1
        ///
        /// ähnelt.
        /// </summary>
        internal static string template3 {
            get {
                return ResourceManager.GetString("template3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;qos&gt;
        ///    &lt;numprobes&gt;10&lt;/numprobes&gt;
        ///    &lt;qosport&gt;17499&lt;/qosport&gt;
        ///    &lt;probesize&gt;1200&lt;/probesize&gt;
        ///    &lt;qosip&gt;#QOSIP#&lt;/qosip&gt;
        ///    &lt;requestid&gt;514&lt;/requestid&gt;
        ///    &lt;reqsecret&gt;1125&lt;/reqsecret&gt;
        ///&lt;/qos&gt;
        /// ähnelt.
        /// </summary>
        internal static string template4 {
            get {
                return ResourceManager.GetString("template4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HTTP/1.1 200 OK
        ///Content-Type: application/xml
        ///X-BLAZE-COMPONENT: qos
        ///X-BLAZE-COMMAND: firewall
        ///Content-Length: #SIZE#
        ///X-BLAZE-SEQNO: 2
        ///
        /// ähnelt.
        /// </summary>
        internal static string template5 {
            get {
                return ResourceManager.GetString("template5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;firewall&gt;
        ///    &lt;ips&gt;
        ///        &lt;ips&gt;#QOSIP#&lt;/ips&gt;
        ///        &lt;ips&gt;#QOSIP#&lt;/ips&gt;
        ///    &lt;/ips&gt;
        ///    &lt;numinterfaces&gt;2&lt;/numinterfaces&gt;
        ///    &lt;ports&gt;
        ///        &lt;ports&gt;17499&lt;/ports&gt;
        ///        &lt;ports&gt;17499&lt;/ports&gt;
        ///    &lt;/ports&gt;
        ///    &lt;requestid&gt;136&lt;/requestid&gt;
        ///    &lt;reqsecret&gt;467&lt;/reqsecret&gt;
        ///&lt;/firewall&gt;
        /// ähnelt.
        /// </summary>
        internal static string template6 {
            get {
                return ResourceManager.GetString("template6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HTTP/1.1 200 OK
        ///Content-Type: application/xml
        ///X-BLAZE-COMPONENT: qos
        ///X-BLAZE-COMMAND: firetype
        ///Content-Length: 89
        ///X-BLAZE-SEQNO: 3
        ///
        ///&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;firetype&gt;
        ///    &lt;firetype&gt;2&lt;/firetype&gt;
        ///&lt;/firetype&gt;
        /// ähnelt.
        /// </summary>
        internal static string template7 {
            get {
                return ResourceManager.GetString("template7", resourceCulture);
            }
        }
    }
}
